using System;
using System.IO;
using System.Text;
using MathLibrary;

namespace GeometryTools
{
    /// <summary>
    /// Provides utility methods for mesh manipulation and export.
    /// </summary>
    public class MeshTools
    {
        /// <summary>
        /// Creates an instanced copy of a mesh at specified positions with optional rotations.
        /// </summary>
        /// <param name="points">Array of positions to place mesh copies.</param>
        /// <param name="mesh">Base mesh to copy.</param>
        /// <param name="rotations">Optional per-instance rotations. If provided, must match points.Length.</param>
        /// <returns>Combined mesh with all instances.</returns>
        public static Mesh CopyMeshToPoints(Vector3[] points, Mesh mesh, Quaternion[]? rotations = null)
        {
            var outMesh = new Mesh();

            // Validate rotation array if provided
            if (rotations != null && rotations.Length != points.Length)
            {
                throw new ArgumentException("Rotation array length must match points array length if provided.");
            }

            // Allocate output arrays
            if (mesh.vertices != null)
                outMesh.vertices = new Vector3[mesh.vertices.Length * points.Length];
            if (mesh.normals != null)
                outMesh.normals = new Vector3[mesh.normals.Length * points.Length];
            if (mesh.uvs0 != null)
                outMesh.uvs0 = new Vector2[mesh.uvs0.Length * points.Length];
            if (mesh.uvs1 != null)
                outMesh.uvs1 = new Vector2[mesh.uvs1.Length * points.Length];
            if (mesh.triangles != null)
                outMesh.triangles = new int[mesh.triangles.Length * points.Length];

            // Copy mesh data for each instance
            int vertexStride = mesh.vertices?.Length ?? 0;
            
            for (int i = 0; i < points.Length; i++)
            {
                Vector3 position = points[i];
                Quaternion rotation = rotations?[i] ?? Quaternion.identity;
                int vertexOffset = i * vertexStride;

                // Copy and transform vertices
                if (mesh.vertices != null && outMesh.vertices != null)
                {
                    for (int j = 0; j < mesh.vertices.Length; j++)
                    {
                        Vector3 vertex = mesh.vertices[j];
                        if (rotations != null)
                            vertex = rotation.RotateVector(vertex);
                        outMesh.vertices[vertexOffset + j] = vertex + position;
                    }
                }

                // Copy normals (no translation, rotation only)
                if (mesh.normals != null && outMesh.normals != null)
                {
                    for (int j = 0; j < mesh.normals.Length; j++)
                    {
                        Vector3 normal = mesh.normals[j];
                        if (rotations != null)
                            normal = rotation.RotateVector(normal);
                        outMesh.normals[vertexOffset + j] = normal;
                    }
                }

                // Copy UVs (no transformation needed)
                if (mesh.uvs0 != null && outMesh.uvs0 != null)
                {
                    for (int j = 0; j < mesh.uvs0.Length; j++)
                        outMesh.uvs0[vertexOffset + j] = mesh.uvs0[j];
                }

                // Copy UVs1 (no transformation needed)
                if (mesh.uvs1 != null && outMesh.uvs1 != null)
                {
                    for (int j = 0; j < mesh.uvs1.Length; j++)
                        outMesh.uvs1[vertexOffset + j] = mesh.uvs1[j];
                }

                // Copy triangles with offset
                if (mesh.triangles != null && outMesh.triangles != null)
                {
                    for (int j = 0; j < mesh.triangles.Length; j++)
                        outMesh.triangles[i * mesh.triangles.Length + j] = mesh.triangles[j] + vertexOffset;
                }
            }

            return outMesh;
        }

        /// <summary>
        /// Exports a mesh to OBJ file format.
        /// </summary>
        /// <param name="mesh">Mesh to export.</param>
        /// <param name="filePath">Output file path.</param>
        public static void WriteMeshToObj(Mesh mesh, string filePath)
        {
            if (mesh == null)
                throw new ArgumentNullException(nameof(mesh));

            using (var writer = new StreamWriter(filePath))
            {
                var sb = new StringBuilder();
                writer.WriteLine("# Generated by GeometryTools");
                
                if (mesh != null)
                {
                    // Write vertices
                    if (mesh.vertices != null)
                    {
                        foreach (Vector3 v in mesh.vertices)
                            sb.AppendFormat("v {0} {1} {2}\n", v.x, v.y, v.z);
                        sb.AppendLine();
                    }

                    // Write normals
                    if (mesh.normals != null)
                    {
                        foreach (Vector3 n in mesh.normals)
                            sb.AppendFormat("vn {0} {1} {2}\n", n.x, n.y, n.z);
                        sb.AppendLine();
                    }

                    // Write texture coordinates
                    if (mesh.uvs0 != null)
                    {
                        foreach (Vector2 uv in mesh.uvs0)
                            sb.AppendFormat("vt {0} {1}\n", uv.x, uv.y);
                        sb.AppendLine();
                    }

                    // Write faces
                    if (mesh.triangles != null)
                    {
                        bool hasNormals = mesh.normals != null;
                        bool hasUVs = mesh.uvs0 != null;

                        for (int i = 0; i < mesh.triangles.Length; i += 3)
                        {
                            // OBJ format uses 1-based indices
                            int v0 = mesh.triangles[i] + 1;
                            int v1 = mesh.triangles[i + 1] + 1;
                            int v2 = mesh.triangles[i + 2] + 1;

                            if (hasUVs && hasNormals)
                                sb.AppendFormat("f {0}/{0}/{0} {1}/{1}/{1} {2}/{2}/{2}\n", v0, v1, v2);
                            else if (hasUVs)
                                sb.AppendFormat("f {0}/{0} {1}/{1} {2}/{2}\n", v0, v1, v2);
                            else if (hasNormals)
                                sb.AppendFormat("f {0}//{0} {1}//{1} {2}//{2}\n", v0, v1, v2);
                            else
                                sb.AppendFormat("f {0} {1} {2}\n", v0, v1, v2);
                        }
                        sb.AppendLine();
                    }
                }

                writer.Write(sb.ToString());
            }
        }
    }
}
